all:
  hosts:
    master1:
      ansible_host: 10.0.0.11
      ip: 10.0.0.11
      access_ip: 10.0.0.11
    master2:
      ansible_host: 10.0.0.12
      ip: 10.0.0.12
      access_ip: 10.0.0.12
    master3:
      ansible_host: 10.0.0.13
      ip: 10.0.0.13
      access_ip: 10.0.0.13
    worker1:
      ansible_host: 10.0.0.21
      ip: 10.0.0.21
      access_ip: 10.0.0.21
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker1:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    # k8s_cluster объединяет все ноды кластера (masters + workers)
    # Это необходимо для Kubespray, так как многие роли применяются ко всем узлам
    # (container runtime, sysctl, kubelet, CNI-плагины, сертификаты)
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
